set( CMAKE_SYSTEM_NAME "Linux" )
set( CMAKE_SYSTEM_PROCESOR "aarch64" )

set( target_triple "aarch64-linux-gnu" )

set( CMAKE_C_COMPILER zig cc )
set( CMAKE_C_COMPILER_TARGET ${target_triple} )
set( CMAKE_CXX_COMPILER zig c++ )
set( CMAKE_CXX_COMPILER_TARGET ${target_triple} )

set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
